# Generated by Django 4.0.6 on 2022-08-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
