# Generated by Django 4.0.6 on 2022-08-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='blogpost_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='blogpost_count',
            field=models.IntegerField(default=0),
        ),
    ]
